// <auto-generated />
using Excel.Improter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Excel.Improter.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210216101115_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Excel.Improter.Models.DatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AyrilanSahe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMAABitmeTarix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMAANomresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMAAQeydiyyatTarixi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EhtiyyatinKategoryasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasilatItkileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlUzreHasilatCemi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlkinEhtiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstisimarVeziyyeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kesfiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kordinat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedaxilVeziyyeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilliGealojiKeshfiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoteberliyiTesdiqlenmemishEhtiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaliqEhtiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaheninAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaheninKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenayeMenimsenilmeSahesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TexnikiSerhedDeyishmesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginInzibatiErazisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YenidenQiymetlendirme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExcelDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
