// <auto-generated />
using System;
using Excel.Improter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Excel.Improter.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210216173227_initial3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Excel.Improter.Models.DatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AyrilanSahe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DMAABitmeTarix")
                        .HasColumnType("datetime2");

                    b.Property<string>("DMAANomresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DMAAQeydiyyatTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EhtiyyatinKategoryasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaydaliQazintiNovu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasilatQaliqlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlUzreHasilatCemi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlkinEhtiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstisimarVeziyyeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kordinat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedaxilVeziyyeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilliGealojiKeshfiyyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaheninAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaheninKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginInzibatiErazisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YataginKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExcelDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
